### ISSUE TITLE
TAD available if parachute open

### ISSUE THREAD

**Issue by Raspu86** [Riouken/cTab#131]
![http://i.imgur.com/8UpXrcJs.jpg](http://i.imgur.com/8UpXrcJ.jpg)

**Comment by nsgundy** [comment]
The parachute inherits from the `Helicopter` class...
Config path: `configfile >> "CfgVehicles" >> "Steerable_Parachute_F"`
Parents: `["Paraglide","ParachuteWest","ParachuteBase","Helicopter","Air","AllVehicles","All"]`
so we need to exclude `ParachuteBase` from available TAD vehicles.
