### ISSUE TITLE
Categorize HelmetCam as night-vision gear or glasses

### ISSUE THREAD

**Issue by nsgundy** [Riouken/cTab#142]
From the BI forums:
> what do you think of cotegorizing it as a facewear item or a night vision item?

The trouble with categorizing the helmet cam item as any of these is that it will be automatically swapped with whatever was in that slot before, whenever the selection is done with a right-click from the inventory. Of course the user can then manually move the helmet cam back to the general inventory and re-add the item that previously occupied that slot.
Categorizing it as night vision might be a good middle-ground since at the moment the helmet cam is near-useless at night and a lot of people seem to elect to not wearing night-vision gear during daytime operations. On the other hand I am not sure if the inherited night-vision capability can be disabled (you don't want someone with just a helmet-cam to be able to press "n" and get night-vision just as if he had proper night-vision gear). Something to look into.

**Comment by nsgundy** [comment]
Tried to create an Arsenal selectable NVG item without the actual NVG capabilities, but wasn't able to.

Ended up changing to glasses.

**Comment by BryanBoru** [comment]
Having the HelmetCam no longer replace equipped items was something most of my unit was begging for. I am having a hard time seeing how making them categorized as NVGs is a good thing if they end up replacing your current NVGs when you take one from Arsenal. Why not categorize them as an Item?

**Comment by nsgundy** [comment]
Hi @BryanBoru, thanks for joining the discussion. To my knowledge (and granted, that's quite limited), there is no "just item" category that will show up in Arsenal. Mine detectors and medi-packs are for example specific item categories that will show up in Arsenal, but also have a function attached to them. So if the HelmetCam item was categorized as a mine detector, you would get warnings about mines in your proximity as well.
I would gladly be proven wrong here.

**Comment by BryanBoru** [comment]
thanks for the reply @nsgundy Yeah I had looked into some of the configs and found the same issues you replied with. Only other possibility is going the route AGM went it their items, but then the arsenal VAS etc will require special configs to slot the cam into items. 
Probably more trouble than its worth. 
In the end, I'd rather it recognized as glasses, as I wouldnt be too frustrated with ending up out in the field without glasses compared to the other slotted items like radios and such.

**Comment by nsgundy** [comment]
Thanks @BryanBoru, I will leave it as glasses for the next update then to see how the community reacts to the change.
