### ISSUE TITLE
fn_processCuratorkey.sqf not yet updated to new cba keybinding.

### ISSUE THREAD

**Issue by Pergor** [Riouken/cTab#144]
Even after 2.1.1. cTab still spams the fn_processCuratorKey-error, resulting in major performance loss (and giant rpts).
It's the same error tfar had prior to the 0.9.7.3-update.

**Comment by nsgundy** [comment]
@Pergor, thanks for the report, I didn't even know about this one. Do you have an example of the RPT error? Haven't been playing lately.

**Comment by nsgundy** [comment]
@Pergor, found it: [TFAR Issue 932](https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/932)
