### ISSUE TITLE
cTab markers not displayed after GroupID change

### ISSUE THREAD

**Issue by whiztler** [Riouken/cTab#156]
### Specs:

- cTab version: 2.2.1.4 HF

- Addons used: @CBA_A3, @cTAB

- Tested where: Editor preview, Dedi MP

### Issue:

cTab does not update the `groupID` list when the `groupID` changes post-init. 

#### Example

I have a script that changes groupID's post-init. This is done because the framework is used by multiple communities/mission makers. The script applies the groupID as follows:
```php
_i = _ADF_preset_companyGroups find _ADF_uGroupID;
if (_i == -1) exitwith {["PRESETS - ERROR! Unknown group or unit. Roster NOT created. Call sign NOT applied. Please use ADF units only!",true] call ADF_fnc_log};
_ADF_uPreset	= ADF_presetData select _i;

// Apply the call sign and freq data
_ADF_uGroup setGroupId [_ADF_uPreset select 0];
```
This script is run on all local clients (except HC) + server. [Script can be found here](https://github.com/whiztler/ADF/blob/master/Core/ADF_clientPreset.sqf)
In-game, quering the groupID with `hint str groupID (group player)` returns the correct\expected result. But cTAB is not displaying any marker on the itemCtab.
In another test ACE3 does display the groupID correctly in the ACE_microDAGR.

In line with my previous query, and your advice on the cTAB BIS Forum topic I have tried to re-initialize cTAB with:
```php
call cTab_fnc_updateLists; // 1.39 B5 > not updating
```
and with
```php
["cTab_updatePulse",cTab_fnc_updateLists] call CBA_fnc_addEventHandler; // not updating
```
Both ^^ with no result.

**Comment by nsgundy** [comment]
Thanks for the detailed report. I have not fired it up yet, but let me ask a question: Are you expecting to see a marker with the call-sign for your own group? Because that's not what currently happens on cTab. There will be a marker (in neon-green) that shows your own position, but no call-sign will be displayed for yourself (as I did expect that you wouldn't be interested in your own call-sign blocking some of the map). And any members of your own group will only show up with a number next to them, depicting the index of the member within the group. So only the groupID of other groups are actually used.
Since calling `setGroupID` doesn't seem to have a global effect, you would want to apply the groupIDs of every single group on every single client, so your client knows the groupIDs of the other clients. Therefore try this (not tested):
``` sqf
// Apply the call sign for all groups
{
	_ADF_xPreset = ADF_presetData select _forEachIndex;
	_x setGroupId [_ADF_xPreset select 0];
} forEach _ADF_preset_companyGroups;
```

**Comment by whiztler** [comment]
Thanks for the prompt reply. Actually I did expect to see the groupID marker on dedi with only 1 player. This has changed recently? It used to work if I recall correctly. Anyway, will test with another player and report back.

The groupID is announced globally in the [script](https://github.com/whiztler/ADF/blob/master/Core/ADF_clientPreset.sqf) at line #158:
```PHP
[[_ADF_uGroup,[_ADF_uPreset select 0]],'setGroupID',true,true] call BIS_FNC_MP;
```
Thanks again for feedback!

**Comment by nsgundy** [comment]
No problem. Yes that was changed a while back in cTab 2.1. I went through some effort to remove clutter.

I missed that line. This command though seems to be executed by every unit in the group. For a group with 10 members, wouldn't that result in the same command being executed 10 times on every client? Or in other words, on a mission with four groups and 40 players, every client will be send out one of these commands, meaning that every client will executed 40x `setGroupID` via `BIS_fnc_MP` where 5x should have been enough. Might be a good idea to move that section to be executed on the server instead, once for all groups, or just have it locally executed for all groups on every client (like I outlined above), not creating any network load.
I obviously don't know enough about your script, but if that setup is static per mission and all of the information is already available at the client, no need to use `BIS_fnc_MP`.

**Comment by whiztler** [comment]
You're totally right. I plan to implement a more efficient option as soon as the script is tested fully, hopefully with https://community.bistudio.com/wiki/remoteExec

**Comment by whiztler** [comment]
Did a test on dedi with other players. All working as expected. Thanks for your assistance.

P.s. presetClient now much more efficient. Thanks for the heads up. Didn't even realize in the first place :)

P.p.s. I saw a post on ACE3 that you offered to integrate/assist with the ACE BFT? Is that on the table? I reckon cTAB is much better than the current ACE3 BFT solution.

**Comment by nsgundy** [comment]
Yes, cTab integration into ACE has been worked on by a small team including myself for a couple of weeks now. There is still lots to do and due to lack of time the progress is a bit sluggish at the moment.Current progress can be tracked here: https://github.com/acemod/ACE3/pull/995
