### ISSUE TITLE
Add night mode to TAD

### ISSUE THREAD

**Issue by nsgundy** [Riouken/cTab#24]
Add a night mode to TAD that will dim the display. Possibly by overlaying a box with black background and a lot of transparency.

**Comment by nsgundy** [comment]
Possibly use auto detection of night time similar to TFAR
`onLoad = "if(sunOrMoon < 0.2)then{((_this select 0) displayCtrl TF_BACKGROUND_ID) ctrlSetText 'path_to_night_background.paa';};";`

**Comment by nsgundy** [comment]
@Raspu86 can I request a night version of the TAD background? The others would be nice as well, but of the ones you have done, TAD would look the coolest.

**Comment by Raspu86** [comment]
Pics or it didnt't happen.

**Comment by nsgundy** [comment]
Well, you earned it :)
[TAD DAY/NIGHT](http://imgur.com/a/dWOlN)
